name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
         
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    -
      name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
        service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
        
    - name: Auth With GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}'

    - name: Debug environment variables
      env:
          DB_HOST: '34.71.134.6354'
          DB_NAME: 'new_connectmate_db_what'
          DB_USER: 'rooter'
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AWS_REGION: 'us-east-13'
      run: |
        echo "Envs:"
        echo "AWS_REGION=${{ env.AWS_REGION }}"
        echo "AWS_REGION=$AWS_REGION"
        echo "DB_HOST=${{ env.DB_HOST }}"
        echo "DB_NAME=${{ env.DB_NAME }}"
        echo "DB_USER=${{ env.DB_USER }}"
        echo "DB_PASSWORD=${{ env.DB_PASSWORD }}"
        # Sensitive values are intentionally omitted for security

    - name: Build and push Docker image to Artifact Registry
      env:
        ARTIFACT_REGISTRY_REGION: us-central1 
        REGION: "us-central1" 
        GAR_LOCATION: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/springboot-backend
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/springboot-backend/connectmate \
                     --build-arg DB_HOST=${{ env.DB_HOST }} \
                     --build-arg DB_NAME=${{ env.DB_NAME }} \
                     --build-arg DB_USER=${{ env.DB_USER }} \
                     --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                     --build-arg AWS_ACCESS_KEY=${{ env.AWS_ACCESS_KEY }} \
                     --build-arg AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
                     --build-arg AWS_REGION=${{ env.AWS_REGION }} \
                     --no-cache .
        docker tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/springboot-backend/connectmate us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/springboot-backend/connectmate:$GITHUB_SHA
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/springboot-backend/connectmate:$GITHUB_SHA
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/springboot-backend/connectmate:latest



    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy connectmate \
          --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/springboot-backend/connectmate \
          --platform=managed \
          --port=3000 \
          --region=us-central1 \
          --allow-unauthenticated 
